# Generated by Django 4.1 on 2023-05-21 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Inscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ecole", models.CharField(max_length=150)),
                ("membre1", models.CharField(max_length=150)),
                ("classe1", models.CharField(max_length=150)),
                ("membre2", models.CharField(max_length=150)),
                ("classe2", models.CharField(max_length=150)),
                ("membre3", models.CharField(max_length=150)),
                ("classe3", models.CharField(max_length=150)),
                ("email", models.EmailField(max_length=254)),
                ("theme", models.CharField(max_length=150)),
                ("article", models.FileField(upload_to="article/")),
            ],
        ),
    ]
